language: node_js
node_js:
  - node
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
script: pnpm test
deploy:
  provider: script
  script: git remote remove origin && git remote add origin https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/$TRAVIS_REPO_SLUG && git symbolic-ref HEAD refs/heads/master && git fetch origin && git branch -u origin/master && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && npm run release
  skip_cleanup: true
  on:
    branch: master
